# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: zip game
      run: zip -9 -r radon_run.love .
    - name: get engine
      run: | 
        curl -OL   https://bitbucket.org/rude/love/downloads/love-0.10.2-macosx-x64.zip
        unzip -a ./love-0.10.2-macosx-x64.zip
    - name: package game
      run: |
        mv love.app radon_run.app
        cp radon_run.love radon_run.app/Contents/Resources/
        cat <<EOT > radon_run.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>BuildMachineOSBuild</key>
            <string>16A323</string>
            <key>CFBundleDevelopmentRegion</key>
            <string>English</string>
            <key>CFBundleDocumentTypes</key>
            <array>
              <dict>
                <key>CFBundleTypeExtensions</key>
                <array>
                  <string>love</string>
                </array>
                <key>CFBundleTypeIconFile</key>
                <string>GameIcon</string>
                <key>CFBundleTypeName</key>
                <string>LÖVE Project</string>
                <key>CFBundleTypeRole</key>
                <string>Viewer</string>
                <key>LSHandlerRank</key>
                <string>Owner</string>
                <key>LSItemContentTypes</key>
                <array>
                  <string>org.love2d.love-game</string>
                </array>
                <key>LSTypeIsPackage</key>
                <integer>1</integer>
              </dict>
              <dict>
                <key>CFBundleTypeName</key>
                <string>Folder</string>
                <key>CFBundleTypeOSTypes</key>
                <array>
                  <string>fold</string>
                </array>
                <key>CFBundleTypeRole</key>
                <string>Viewer</string>
                <key>LSHandlerRank</key>
                <string>None</string>
              </dict>
              <dict>
                <key>CFBundleTypeIconFile</key>
                <string>Document</string>
                <key>CFBundleTypeName</key>
                <string>Document</string>
                <key>CFBundleTypeOSTypes</key>
                <array>
                  <string>****</string>
                </array>
                <key>CFBundleTypeRole</key>
                <string>Editor</string>
              </dict>
            </array>
            <key>CFBundleExecutable</key>
            <string>love</string>
            <key>CFBundleIconFile</key>
            <string>OS X AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.airthings.radon_run</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>radon_run</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>0.10.2</string>
            <key>CFBundleSignature</key>
            <string>LoVe</string>
            <key>CFBundleSupportedPlatforms</key>
            <array>
              <string>MacOSX</string>
            </array>
            <key>DTCompiler</key>
            <string>com.apple.compilers.llvm.clang.1_0</string>
            <key>DTPlatformBuild</key>
            <string>8B62</string>
            <key>DTPlatformVersion</key>
            <string>GM</string>
            <key>DTSDKBuild</key>
            <string>16B2649</string>
            <key>DTSDKName</key>
            <string>macosx10.12</string>
            <key>DTXcode</key>
            <string>0810</string>
            <key>DTXcodeBuild</key>
            <string>8B62</string>
            <key>LSApplicationCategoryType</key>
            <string>public.app-category.games</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSHumanReadableCopyright</key>
            <string>© 2020 Airthings Development Team</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>UTExportedTypeDeclarations</key>
          </dict>
          </plist>
        EOT
        
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'radon_run.app'
